### ISSUE TITLE
suggestion changing "and" to "or" in 5.1.1

### ISSUE THREAD

**Issue by tsingkong** [loongson/la-asm-manual#13]
I think changing 
`The assembler directive that defines a symbol type is .type, which is often followed by types @function and @object, respectively, indicating that the current symbol is a function and a variable.`
to 
`The assembler directive that defines a symbol type is .type, which is often followed by types @function or @object, respectively, indicating that the current symbol is a function or a variable.`
is better.

**Comment by SixWeining** [comment]
addressed by #15
