### ISSUE TITLE
A slip of pen in chapter 9

### ISSUE THREAD

**Issue by zhaoqi5** [loongson/la-asm-manual#14]
Looks there is a slip of pen in chapter 9. As shown below.

![2024-08-16_11-10](https://github.com/user-attachments/assets/cda7f02c-9034-4c24-8858-4a5dac754cca)

We don't have `lu32i.w` and `lu52i.w` instructions, so they should be `lu32i.d` and `lu52i.d`.

In addition, `lu52i.d` has three operations, it should be `lu52i.d $rd, $rd, si12`.

**Comment by SixWeining** [comment]
addressed by #15
