### ISSUE TITLE
bit width of FRs

### ISSUE THREAD

**Issue by tsingkong** [loongson/la-asm-manual#7]
About bit width of FRs, adoc/CHAPTER-3.Register/3.2-Floating-Point_Register.adoc tells as:
`
The bit
width of FR is 32 bits, which only implements floating-point instructions that operate on single
precision floating-point numbers and word integers. Usually, the bit width of FR is 64 bits,
regardless of whether it is an LA32 or LA64 architecture.
`
which confuse me.

**Comment by ypf79** [comment]
When only single-precision floating-point and word integer floating-point instructions are implemented, the bit width of FR is 32 bits. In other cases, whether LA32 or LA64, the bit width of FR is 64 bits. The next release will be modified.

**Comment by ypf79** [comment]
> About bit width of FRs, adoc/CHAPTER-3.Register/3.2-Floating-Point_Register.adoc tells as: `The bit width of FR is 32 bits, which only implements floating-point instructions that operate on single precision floating-point numbers and word integers. Usually, the bit width of FR is 64 bits, regardless of whether it is an LA32 or LA64 architecture.` which confuse me.

When only single-precision floating-point and word integer floating-point instructions are implemented, the bit width of FR is 32 bits. In other cases, whether LA32 or LA64, the bit width of FR is 64 bits. The next release will be modified.

**Comment by SixWeining** [comment]
addressed by #15
